[PyOV] Fix several issues with wheel building dependencies (#27752)
### Details:
- `packaging` is a dependency of `setuptools`. When installed with
version lower than 22.0 it results in `TypeError: canonicalize_version()
got an unexpected keyword argument 'strip_trailing_zero'` when building
wheel. `setuptools` claims it's an expected behavior, does not enforce
that constraint and recommends to add the constraint ourselves. More
information: https://github.com/pypa/setuptools/issues/4483
- `ImportError: cannot import name 'splat' from 'jaraco.functools'` has
been fixed in `setuptools==75.4.0`. More information:
https://github.com/pypa/setuptools/commit/8d518af4563ae3a448c6062c12d03dee3d78a0c5
- `Failed to detect ABI Tag via setuptools.command.bdist_wheel` - the
functionality has been added in `setuptools==70.1.0`, that's where the
new lower bound comes from. More context:
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/wheel/CMakeLists.txt#L15

### Tickets:
 - CVS-157981

---------

Signed-off-by: p-wysocki <przemyslaw.wysocki@intel.com>